version: '2'
# version: '2.1'
volumes:
    resin-data:
    # Define your own volumes or reuse existing ones if your are in a multicontainer setup
    #volume_homeassistant:
services:
  node-red:
    build: ./node-red
    environment:
      - UDEV=1
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    volumes:
      - 'resin-data:/data'
    restart: always
    privileged: true
    network_mode: host
    labels:
      io.balena.features.supervisor-api: '1'
      io.balena.features.dbus: '1'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
      #- "/dev/i2c-0:/dev/i2c-0"    # TODO. Modif à faire pour l'activer car utiliser pour les shields normalement
      - "/dev/i2c-4:/dev/i2c-4"
      - "/dev/ttyACM0:/dev/ttyACM0"   #Port série
      - "/dev/input/by-path/:/dev/input/by-path/"   #pour le noeud clavier avec les noeud gpio
    ports:
      - 80:80
      - 1883:1883
      - 1400:1400
      - 1880:1880
      - 1980:1880
  scp-server:
    network_mode: host
    restart: always
    build:
      context: ./balena-scpserver
    privileged: false
    labels:
      io.balena.features.dbus: 1
    volumes:
      - resin-data:/data
    ports:
      - "22:22/udp"
      - "22:22/tcp"  