version: '2'
volumes:
    resin-data:
services:
  node-red:
    build: ./node-red
    environment:
      - UDEV=1
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    volumes:
      - 'resin-data:/data'
    restart: always
    privileged: true
    network_mode: host
    labels:
      io.balena.features.supervisor-api: '1'
      io.balena.features.dbus: '1'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/i2c-0:/dev/i2c-0"
      - "/dev/i2c-4:/dev/i2c-4"
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/input/by-path/:/dev/input/by-path/"
    ports:
      - 80:80
      - 1883:1883
      - 1400:1400
      - 1880:1880
      - 1980:1880
      
      
