version: '2.1'
# version: '2'
# Define your own volumes or reuse existing ones if your are in a multicontainer setup
volumes:
    node-red-data:
    kodi-data:
    kodi2-data:
    #volume_homeassistant:
    nodered_working_dir:
    node_modules:
    redis-data:
    knxd-data:
    knxd2-data:
    knxd3-data:
    knxd4-data:
    knxd5-data:
    #browser-data:
services:
  node-red:
    build: ./node-red
    environment:
      - UDEV=1  #active le hotplug des périphérique USB par ex mais il faut que privileged true soit déclarer aussi # see https://www.balena.io/docs/reference/base-images/base-images/#working-with-dynamically-plugged-devices
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    volumes:
      - node-red-data:/data
      - nodered_working_dir:/usr/src/app
      - node_modules:/usr/local/lib/node_modules
    restart: always
    privileged: true
    network_mode: host
    labels:
      io.balena.features.supervisor-api: '1'
      io.balena.features.dbus: '1'
      #???io.balena.features.kernel-modules: '1'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
      #- "/dev/i2c-0:/dev/i2c-0"    # TODO. Modif à faire pour l'activer car utiliser pour les shields normalement
      - "/dev/i2c-4:/dev/i2c-4"
      - "/dev/ttyACM0:/dev/ttyACM0"   #Port série
      - "/dev/input/by-path/:/dev/input/by-path/"   #pour le noeud clavier avec les noeud gpio
    ports:
      - 80:80
      - 1883:1883
      - 1400:1400
      - 1880:1880
      - 1980:1880
  scp-server:
    network_mode: host
    restart: always
    build:
      context: ./scp-server
    privileged: false
    labels:
      io.balena.features.dbus: 1
    volumes:
      - node-red-data:/data
      - nodered_working_dir:/usr/src/app
      - node_modules:/usr/local/lib/node_modules
    ports:
      - "22:22/udp"
      - "22:22/tcp"  
  samba:
    #  hostname: samba  # doesn't work
    image: dastrasmue/rpi-samba 
    command:  -u "cta:domotique" -s "node-red-data:/mount/node-red-data:rw:cta" -s "kodi-data:/mount/kodi-data:rw:cta" -s "kodi2-data:/mount/kodi2-data:rw:cta" -s "redis-data:/mount/redis-data:rw:cta" -s "knxd-data:/mount/knxd-data:rw:cta" -s "knxd2-data:/mount/knxd2-data:rw:cta" -s "knxd-data3:/mount/knxd-data3:rw:cta" -s "knxd4-data:/mount/knxd4-data:rw:cta" -s "knxd5-data:/mount/knxd5-data:rw:cta"
    volumes:
      - 'node-red-data:/mount/node-red-data'
      - 'kodi-data:/mount/kodi-data'
      - 'kodi2-data:/mount/kodi2-data'
      - 'redis-data::/mount/redis-data'
      - 'knxd-data:/mount/knxd-data'
      - 'knxd2-data:/mount/knxd2-data'
      - 'knxd3-data:/mount/knxd3-data'
      - 'knxd4-data:/mount/knxd4-data'
      - 'knxd5-data:/mount/knxd5-data'
    ports:
    #  - "137:137"
    #  - "137:137/udp"
      - "139:139"
      - "445:445"
    #  - "445:445/udp"
