version: '2.1'

# Summary of global ENV Variables to setup in Balena:
# SCP_PASSWORD: balena

# Define your own volumes or reuse existing ones if your are in a multicontainer setup
volumes:
  volume_homeassistant:

services:
  scp-server:
    network_mode: host
    restart: always
    build:
      context: ./balena-scpserver
    privileged: false
    labels:
      io.balena.features.dbus: 1
    volumes:
      - volume_homeassistant:/config
    ports:
      - "22:22/udp"
      - "22:22/tcp"
